require("0xbdg.config.nvim-tree")
require("0xbdg.config.lualine")
require("0xbdg.config.telescope")
require("0xbdg.config.bufferline")
require("0xbdg.config.lsp_config")
require("0xbdg.config.rust_conf")
require("0xbdg.config.treesitter")
require("0xbdg.config.dap_conf")
